CREATE DATABASE [BucketList] 
GO
ALTER DATABASE BucketList MODIFY FILE 
( NAME = N'BucketList' , SIZE = 3048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
GO
ALTER DATABASE BucketList MODIFY FILE 
( NAME = N'BucketList_log' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
